# Default repolinter ruleset for Twitter open source repositories.
#
# This excludes some rules from the default repolinter ruleset because these
# files are inherited from the org-wide .github repository:
#
# - code-of-conduct-file-exists
# - code-of-conduct-file-contains-email
# - security-file-exists
# - github-issue-template-exists
# - github-pull-request-template-exists

"$schema": "https://raw.githubusercontent.com/todogroup/repolinter/master/rulesets/schema.json"
version: 2
axioms:
  linguist: language
  licensee: license
  packagers: packager
rules:
  license-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - LICENSE*
        - COPYING*
        nocase: true
  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - README*
        nocase: true
  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - "{docs/,.github/,}CONTRIB*"
        nocase: true
  binaries-not-present:
    level: error
    rule:
      type: file-type-exclusion
      options:
        type:
        - "**/*.exe"
        - "**/*.dll"
        - "!node_modules/**"
  integrates-with-ci:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
        - ".gitlab-ci.yml"
        - ".travis.yml"
        - appveyor.yml
        - ".appveyor.yml"
        - circle.yml
        - ".circleci/config.yml"
        - Jenkinsfile
        - ".drone.yml"
        - ".github/workflows/*"
        - azure-pipelines.yml
  source-license-headers-exist:
    level: warning
    rule:
      type: file-starts-with
      options:
        globsAll:
        - "**/*.{c,cc,c++,go,java,js,py,scala}"
        - "!node_modules/**"
        lineCount: 5
        patterns:
        - Copyright
        - License
        flags: i
  javascript-package-metadata-exists:
    level: error
    where:
    - language=javascript
    rule:
      type: file-existence
      options:
        globsAny:
        - package.json
  ruby-package-metadata-exists:
    level: error
    where:
    - language=ruby
    rule:
      type: file-existence
      options:
        globsAny:
        - Gemfile
  java-package-metadata-exists:
    level: error
    where:
    - language=java
    rule:
      type: file-existence
      options:
        globsAny:
        - pom.xml
        - build.xml
        - build.gradle
  python-package-metadata-exists:
    level: error
    where:
    - language=python
    rule:
      type: file-existence
      options:
        globsAny:
        - setup.py
        - requirements.txt
  objective-c-package-metadata-exists:
    level: error
    where:
    - language=objective-c
    rule:
      type: file-existence
      options:
        globsAny:
        - Cartfile
        - Podfile
        - "*.podspec"
  swift-package-metadata-exists:
    level: error
    where:
    - language=swift
    rule:
      type: file-existence
      options:
        globsAny:
        - Package.swift
  erlang-package-metadata-exists:
    level: error
    where:
    - language=erlang
    rule:
      type: file-existence
      options:
        globsAny:
        - rebar.config
  elixir-package-metadata-exists:
    level: error
    where:
    - language=elixir
    rule:
      type: file-existence
      options:
        globsAny:
        - mix.exs
  license-detectable-by-licensee:
    level: 'off'
    where:
    - license=*
    rule:
      type: license-detectable-by-licensee
      options: {}
